// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddBalanceAccount(ctx context.Context, arg AddBalanceAccountParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	FetchAccounts(ctx context.Context, arg FetchAccountsParams) ([]Account, error)
	FetchEntries(ctx context.Context, arg FetchEntriesParams) ([]Entry, error)
	FetchTransfer(ctx context.Context, arg FetchTransferParams) ([]Transfer, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateBalanceAccount(ctx context.Context, arg UpdateBalanceAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
